### ISSUE TITLE
Add .gitattributes to exclude unneeded files for packages

### ISSUE THREAD

**Issue by elazar** [phergie/phergie-irc-bot-react#21]
See [this article](http://www.sitepoint.com/mastering-composer-tips-tricks/). Create a `.gitattributes` file in the root of the repo with entries for files like those under `tests`, `.travis.yml`, and others not needed by end users.

**Comment by tomzx** [comment]
Any reason this is still open considering a PR was merged?

**Comment by elazar** [comment]
Think it was just an oversight. Thanks for pointing it out @tomzx. :)
