### ISSUE TITLE
HHVM test failure

### ISSUE THREAD

**Issue by elazar** [phergie/phergie-irc-bot-react#28]
Travis is [encountering a failure](https://travis-ci.org/phergie/phergie-irc-bot-react/jobs/64842791) when running the test suite under HHVM 3.5.0:

```
Fatal error: Class Mock_AbstractPlugin_6cda3dc5 contains abstract method (getSubscribedEvents) and must therefore be declared abstract or implement the remaining methods in /home/travis/build/phergie/phergie-irc-bot-react/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(301) : eval()'d code on line 1
```

**Comment by nick-jones** [comment]
This looks to be due to https://github.com/facebook/hhvm/issues/5170 (see also https://github.com/sebastianbergmann/phpunit-mock-objects/issues/223)

Tests are passing with the HHVM nightly build.. not sure what the best course of action is, though.

**Comment by elazar** [comment]
Unfortunately, last I checked, Travis CI [stopped supporting](https://github.com/travis-ci/travis-ci/issues/3788#issuecomment-97171678) HHVM nightly builds pending an upgrade of Ubuntu to Trusty. So, for the moment, nothing may be all we can do. :(

**Comment by Renegade334** [comment]
Yup, this is due to hhvm failing to reflect abstract classes properly, which broke testing when the phpunit version was upgraded.

The fix has yet to be committed to a stable hhvm branch.

**Comment by elazar** [comment]
Odd. I followed facebook/hhvm#5170, which lead to facebook/hhvm#5236 and https://reviews.facebook.net/D37899. The latter seemed to indicate that the fix was accepted, but neither indicates when it might be merged. The former was closed on 5/5. The last two releases of HHVM, [3.7.0](https://github.com/facebook/hhvm/tree/HHVM-3.7.0) and [3.7.1](https://github.com/facebook/hhvm/tree/HHVM-3.7.1), were tagged on 4/27 and 5/27 respectively. 3.7.1 doesn't contain the fix, so obviously it wasn't merged before then. I can't speak to how Facebook manages the flow of code to master, but offhand, it doesn't seem very intuitive.

**Comment by Renegade334** [comment]
Commits to master aren't automatically merged into stable hhvm branches, so we'll have to wait and see.

**Comment by svpernova09** [comment]
Looks like HHVM is passing again: https://travis-ci.org/phergie/phergie-irc-bot-react

**Comment by elazar** [comment]
:+1: Guessing the fix was merged and Travis updated their version of HHVM. It's probably OK to close this.
