### ISSUE TITLE
guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by elstamey** [phergie/phergie-irc-bot-react#46]
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

**Comment by svpernova09** [comment]
This *shouldn't* be a big deal. Give it a shot and we should be good if the tests pass.

**Comment by elazar** [comment]
I'd think this would be related to a plugin being installed? phergie-irc-bot-react doesn't use guzzle/guzzle or pull in anything that does so far as I know.

**Comment by elstamey** [comment]
I cannot tell in the `composer.lock` where the dependency comes in, but it's coming from somewhere.  I didn't receive this warning on tableflip updates.

**Comment by sitedyno** [comment]
> ┌─[shccvga@sound-closet] - [~/projects/phergie-irc-bot-react] - [2016-08-03 10:03:01]
> └─[0] <git:(master f8ee710 )> composer why guzzle/guzzle
> satooshi/php-coveralls  v0.6.1  requires  guzzle/guzzle (>=3.0)

**Comment by elstamey** [comment]
Thanks!  :)

It looks like it would also be a difference between version 3 and version 5.

`"suggest": {
                "guzzlehttp/guzzle": "Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated."
            },`

**Comment by elstamey** [comment]
The `satooshi/php-coveralls` package is pulled in in composer by `phergie/phergie-irc-bot-react-development` and in travis by codeclimate. 

So I guess the update MAY need to be applied in `phergie/phergie-irc-bot-react-development`

**Comment by svpernova09** [comment]
@elstamey 👍 

If it's not our package, not much we can do here since it's still only a warning. Feel free to close. Also may want to glance at that repo's issues and see if they are aware.

Thanks for looking into this!

**Comment by elstamey** [comment]
I'm closing this in favor of fixing in the phergie/phergie-irc-bot-react-development package.
